# Generated by Django 6.0.4 on 2026-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SAFETY_OFFICER', 'Safety Officer'), ('VIEWER', 'Viewer')], default='SAFETY_OFFICER', help_text='Determines which API operations this user may perform.', max_length=32),
        ),
    ]
