# Generated by Django 6.0.4 on 2026-05-31 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_spec_alignment'),
        ('sitemap', '0001_initial'),
        ('workers', '0003_worker_phone_worker_role_alter_worker_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='location',
            field=models.JSONField(blank=True, help_text='GPS coords: {lat, lng}', null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='alert_snapshots/'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PPE_VIOLATION', 'PPE violation'), ('SOS', 'SOS'), ('ZONE_BREACH', 'Zone breach'), ('INACTIVITY', 'Inactivity')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('AI_CAMERA', 'AI Camera'), ('SMART_VEST', 'Smart Vest'), ('SIMULATED', 'Simulated')], default='AI_CAMERA', max_length=32),
        ),
        migrations.CreateModel(
            name='AlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PPE_VIOLATION', 'PPE violation'), ('SOS', 'SOS'), ('ZONE_BREACH', 'Zone breach'), ('INACTIVITY', 'Inactivity')], max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold_seconds', models.IntegerField(default=300, help_text='For inactivity: seconds before alert')),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemap.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('class_name', models.CharField(help_text='YOLO class e.g. no-hardhat, hardhat', max_length=50)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField(help_text='[x1, y1, x2, y2]')),
                ('frame_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
            ],
            options={
                'ordering': ['-frame_timestamp'],
            },
        ),
    ]
