# Generated by Django 6.0.4 on 2026-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alert_location_alert_snapshot_alter_alert_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='camera_id',
            field=models.CharField(blank=True, default='', help_text='Identifier of the camera/edge source that raised this alert, if any', max_length=64),
        ),
    ]
