# Generated by Django 6.0.4 on 2026-09-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PPE_VIOLATION', 'PPE violation'), ('SOS', 'SOS'), ('ZONE_BREACH', 'Zone breach'), ('INACTIVITY', 'Inactivity'), ('VEHICLE_PROXIMITY', 'Vehicle proximity')], max_length=32),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='alert_type',
            field=models.CharField(choices=[('PPE_VIOLATION', 'PPE violation'), ('SOS', 'SOS'), ('ZONE_BREACH', 'Zone breach'), ('INACTIVITY', 'Inactivity'), ('VEHICLE_PROXIMITY', 'Vehicle proximity')], max_length=32),
        ),
    ]
