# Generated by Django 6.0.4 on 2026-05-31 15:19

import django.db.models.deletion
from django.db import migrations, models


def migrate_zone_strings_to_fk(apps, schema_editor):
    Worker = apps.get_model("workers", "Worker")
    Zone = apps.get_model("sitemap", "Zone")

    zone_names = (
        Worker.objects.exclude(zone_name="")
        .values_list("zone_name", flat=True)
        .distinct()
    )
    zone_map = {}
    for name in zone_names:
        if not name:
            continue
        zone, _ = Zone.objects.get_or_create(name=name[:100], defaults={"description": ""})
        zone_map[name] = zone

    for worker in Worker.objects.exclude(zone_name=""):
        zone = zone_map.get(worker.zone_name)
        if zone:
            worker.zone_id = zone.id
            worker.save(update_fields=["zone_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("sitemap", "0001_initial"),
        ("workers", "0002_alter_worker_field_lengths"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="worker",
            name="role",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.RenameField(
            model_name="worker",
            old_name="zone",
            new_name="zone_name",
        ),
        migrations.AddField(
            model_name="worker",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="sitemap.zone",
            ),
        ),
        migrations.RunPython(migrate_zone_strings_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="worker",
            name="zone_name",
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CHECK_IN", "Check In"),
                            ("CHECK_OUT", "Check Out"),
                            ("IDLE_START", "Idle Start"),
                            ("IDLE_END", "Idle End"),
                            ("ZONE_ENTER", "Zone Enter"),
                            ("ZONE_EXIT", "Zone Exit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="workers.worker",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sitemap.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SmartVest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vest_id", models.CharField(db_index=True, max_length=50, unique=True)),
                ("firmware_version", models.CharField(blank=True, default="", max_length=20)),
                ("battery_level", models.IntegerField(default=100, help_text="0-100 percent")),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("sos_active", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_vest",
                        to="workers.worker",
                    ),
                ),
            ],
            options={
                "ordering": ["-registered_at"],
            },
        ),
    ]
