# Generated by Django 6.0.4 on 2026-09-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='camera_ids',
            field=models.JSONField(blank=True, default=list, help_text='Identifiers of cameras assigned to monitor this zone'),
        ),
    ]
